package handler

import (
	"encoding/json"
	"net/http"

	"trade-kit-sidecar/api"
)

// ListRecipes returns all available recipes and their status.
func (h *Handlers) ListRecipes(w http.ResponseWriter, r *http.Request) {
	api.WriteJSON(w, http.StatusOK, h.runner.List())
}

// StartRecipe starts a recipe by ID.
func (h *Handlers) StartRecipe(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	var body json.RawMessage
	json.NewDecoder(r.Body).Decode(&body)

	if err := h.runner.Start(id, body); err != nil {
		api.WriteError(w, http.StatusBadRequest, err.Error())
		return
	}
	api.WriteOK(w)
}

// StopRecipe stops a running recipe.
func (h *Handlers) StopRecipe(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if err := h.runner.Stop(id); err != nil {
		api.WriteError(w, http.StatusNotFound, err.Error())
		return
	}
	api.WriteOK(w)
}

// GetRecipeSignals returns signals generated by a recipe.
func (h *Handlers) GetRecipeSignals(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	signals, err := h.runner.Signals(id)
	if err != nil {
		api.WriteError(w, http.StatusNotFound, err.Error())
		return
	}
	api.WriteJSON(w, http.StatusOK, signals)
}
